//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEmployeeCustomerOrder
    {
        public int Role { get; set; }
        public string FullName { get; set; }
        public int Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public int OrderID { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Shipping_Address { get; set; }
        public int Status { get; set; }
        public int Payment_Method { get; set; }
    }
}
