//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string FullName { get; set; }
        public string Email { get; set; }
        public System.DateTime DoB { get; set; }
        public string Mobile { get; set; }
        public string City { get; set; }
        public decimal Salary { get; set; }
        public int EmployeeID { get; set; }
        public int UserID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
